# Generated by Django 3.2.12 on 2022-02-25 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_dashboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='None', upload_to=student_dashboard.models.StudentProfile.nameFile)),
                ('DOB', models.DateField(max_length=8)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
