# Generated by Django 3.2.12 on 2022-03-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0002_studentmarkdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='english_mark',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='malayalam_mark',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='maths_mark',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='science_mark',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='total_mark',
            field=models.DecimalField(blank=True, decimal_places=5, default=100.0, max_digits=10, null=True),
        ),
    ]
