# Generated by Django 3.2.12 on 2022-03-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0003_auto_20220308_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='english_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='malayalam_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='maths_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='science_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='total_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
