# Generated by Django 3.2.12 on 2022-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0008_alter_studentmarkdetails_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='grade',
            field=models.CharField(blank=True, choices=[('90-100', 'A+'), ('80-89', 'A'), ('70-79', 'B+'), ('50-69', 'B'), ('40-50', 'P'), ('0-39', 'F')], default='0-39', max_length=10, null=True),
        ),
    ]
