# Generated by Django 3.2.12 on 2022-03-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0009_alter_studentmarkdetails_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='grand_total',
            field=models.IntegerField(blank=True, default=400, null=True),
        ),
    ]
