# Generated by Django 3.2.12 on 2022-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0010_alter_studentmarkdetails_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='final_result',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarkdetails',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
